apiVersion: v1
kind: Service
metadata:
  name: odoo-svc
  namespace: icgroup
  labels:
    env: prod
    app: odoo
spec:
  type: NodePort
  ports:
    - name: odoo
      port: 8069
      targetPort: 8069
      protocol: TCP
      nodePort: 30010
  selector:
    app: odoo