apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgadmin-pv
  namespace: icgroup
  labels:
    env: prod
    app: pgadmin
    type: local
spec: 
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  hostPath: 
    path: /data-pgadmin
