apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: icgroup
  labels:
    env: prod
    app: postgres
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /data-postgres
---