apiVersion: apps/v1
kind: Deployment
metadata:
  name: ic-webapp-deploy
  namespace: icgroup
  labels:
    env: prod
    app: ic-webapp
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: ic-webapp
  template:
    metadata:
      labels:
        app: ic-webapp
    spec:
      containers:
        - name: ic-webapp
          image: ulrichsteve/ic-webapp:1.0
          ports:
            - containerPort: 80
          env:
            - name: ODOO_URL
              valueFrom:
                configMapKeyRef:
                  name: ic-webapp-cm
                  key: ODOO_URL
            - name: PGADMIN_URL
              valueFrom:
                configMapKeyRef:
                  name: ic-webapp-cm
                  key: PGADMIN_URL
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"