apiVersion: v1
kind: Service
metadata:
  name: ic-webapp-svc
  namespace: icgroup
  labels:
    env: prod
    app: ic-webapp
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: ic-webapp-port
      nodePort: 30009
  selector:
    app: ic-webapp